Add basic Phoenix bindings support
liveviewnative/liveview-client-swiftui pull request #166
Opened 2023-02-02 18:03 UTC by carson-katri

This is the beginning of support for the bindings referenced in #159 

I have added support for `phx-window-focus` and `phx-window-blur` to test the concept.

> **Note** Those particular events seem to be broken in LiveView currently: https://github.com/phoenixframework/phoenix_live_view/issues/2161

I don't believe this overlaps with #164.

2023-02-02 18:14 UTC, carson-katri commented on Sources/LiveViewNative/BuiltinRegistry.swift
> +            if element.tag == "button" {
I'm not sure if there should be a more general purpose way of representing that an element handles the event internally. Is this rare enough to just handle the few edge cases?

2023-02-02 18:40 UTC, carson-katri commented on Sources/LiveViewNative/BuiltinRegistry.swift
> +            if element.tag == "text-field" || element.tag == "secure-field" {
Another special case is needed for `phx-focus`/`phx-blur`, so this may be fairly common.

2023-02-28 22:09 UTC, carson-katri commented
I added a new property wrapper, `@Event`. It provides a mechanism for sending events with automatic debounce/throttle handling.
It requires the name of the attribute that holds the event name, and an event type. It will automatically check for `phx-debounce`/`phx-throttle` attributes.

```swift
struct MyCounterElement: View {
  @Event("on-increment", type: "click") private var increment

  var body: some View {
    MyCounterView(onIncrement: {
      increment(["new-value": 10]) {
        // on complete
      }
    })
  }
}
```
There's probably also a way to have the debounce/throttle checking happen on the `LiveViewCoordinator` side, but I'm not sure exactly how that would look.

@shadowfacts Let me know your thoughts on this.

2023-03-01 20:52 UTC, shadowfacts requested changes
I left some minor suggestions, but overall I like the `@Event` approach for accessing event handlers.

The one part of this PR I'm not a fan of is the special casing for views that handle certain events internally, like you mentioned. Perhaps the views that do so could communicate that up to the event handler wrappers with view preferences or something similar?

Though come to think of it, we don't want that information to propagate up out of the particular element. I'm not sure SwiftUI has a good mechanism for that :/

2023-03-01 20:52 UTC, shadowfacts commented on Sources/LiveViewNative/Property Wrappers/ObservedElement.swift
> +    public var projectedValue: AnyPublisher<Void, Never> {
This can be `some Publisher<Void, Never>` to avoid the erasure

2023-03-01 20:52 UTC, shadowfacts commented on Sources/LiveViewNative/Property Wrappers/Event.swift
> +    }
I also don't think this initializer is necessary, again because of the ExpressibleByStringLiteral conformance

2023-03-01 20:52 UTC, shadowfacts commented on Sources/LiveViewNative/Property Wrappers/Event.swift
> +    public init(event: String, type: String) {
I'd document how this initializer differs from the attribute name one

2023-03-02 17:55 UTC, carson-katri commented
Improved the event handling to send the `phx-target` value for the `"cid"` key. Now events in a live component will be handled correctly.

2023-03-03 18:34 UTC, shadowfacts approved these changes
Nice work!

2023-03-03 19:16 UTC, merged