Add @Attribute property wrapper
liveviewnative/liveview-client-swiftui pull request #253
Opened 2023-02-28 16:25 UTC by carson-katri

As discussed in #250

This adds the `@Attribute` property wrapper and an `AttributeDecodable` protocol. I incorporated its usage into a few Views to start, but this can be expanded to other Views if everything checks out.

2023-03-01 20:33 UTC, shadowfacts requested changes

2023-03-01 20:33 UTC, shadowfacts commented on Sources/LiveViewNative/Property Wrappers/Attribute.swift
> +    }
I don't think this initializer is necessary, since AttributeName conforms to ExpressibleByStringLiteral

2023-03-02 16:38 UTC, carson-katri commented
I added a `transform` argument (similar to what Swift Argument Parser has) for cases where the type doesn't conform to `AttributeDecodable`, or to provide a more custom decoding process for an attribute.

2023-03-03 18:37 UTC, shadowfacts approved these changes

2023-03-03 19:27 UTC, merged